<?php
if (!defined('IN_BOOT')) {
    exit('Access Denied');
}

class DbMessageCenter_KuaidiCompanyList extends Model
{
    const DB_PREFIX = 'message_center.kuaidi_companyList';
    const REDIS_KEY = 'mc:kdl:';

    const STATUS_NORMAL = 1;
    const STATUS_CLOSE = 2;

    public static $status = [
        self::STATUS_NORMAL => '正常',
        self::STATUS_CLOSE => '关闭',
    ];

    public function __construct()
    {
        $this->setTableName(self::DB_PREFIX);
        parent::__construct();
    }

    public static function getInfoKey($id)
    {
        return self::REDIS_KEY . 'id:' . $id;
    }

    /**
     * 获取本地快递公司信息
     * @param $id
     * @return mixed
     * [
     *  id
     *  companyName
     *  companyEnName
     *  companyNum
     *  status
     * ]
     */
    public function getInfoByIdOfCache($id)
    {
        $key = self::getInfoKey($id);
        $result = $this->proxyModelSearchWithFileCahe($key, [
            $this, 'find'
        ], [
            [
                'id' => $id
            ],
            'name as companyName, enName as companyEnName,  num as companyNum, status'
        ]);
        if (!empty($result)) {
            $result['id'] = $id;
        }
        return $result;
    }

    public static function clearInfoCacheById($id)
    {
        $key = self::getInfoKey($id);
        Cache_File::getInstance()->del($key);
    }

    public static function getIdByCompanyNumKey($companyNum)
    {
        return self::REDIS_KEY . 'companyNum:' . $companyNum;
    }

    public function getIdByCompanyNumOfCache($companyNum)
    {
        $key = self::getIdByCompanyNumKey($companyNum);
        $result = $this->proxyModelSearchWithFileCahe($key, [
            $this, 'find'
        ], [
            [
                'num' => $companyNum
            ],
            'id'
        ]);
        return empty($result) ? 0 : $result['id'];
    }

    public static function clearIdCacheByCompanyNum($companyNum)
    {
        $key = self::getIdByCompanyNumKey($companyNum);
        Cache_File::getInstance()->del($key);
    }

    /**
     * 获取三方快递公司信息
     * @param $id
     * @param $appId
     * @return mixed
     */
    public function getOtherInfoById($id, $appId)
    {
        return DbMessageCenter_KuaidiOtherCompanyList::getInstance()->
        getInfoByCompanyListIdOfCache($id, $appId);
    }

    public function update($data, $condition = null)
    {
        $result = parent::update($data, $condition); // TODO: Change the autogenerated stub
        if($result && ($id = self::getWhereConditionValue($condition, 'id'))){
            self::clearInfoCacheById($id);
        }
        return $result;
    }

    public function insert($data = array())
    {
        $result = parent::insert($data); // TODO: Change the autogenerated stub
        if ($result) {
            self::clearIdCacheByCompanyNum($data['companyNum']);
            self::clearInfoCacheById($this->lastInsertId());
        }
        return $result;
    }

}